name: BlockPickUp
main: DeBePlugins\BlockPickUp\BlockPickUp
version: DeBe
api: [1.6.0]
author: DeBe

permissions:
 debe.op:
  default: op
  description: DeBePlugins
  children:
   debe.blockpickup.use:
    default: true;
    description: BlockPickUp - Use
