name: Korean
main: DeBePlugins\Korean\Korean
version: DeBe
api: [1.6.0]
author: DeBe

commands:
 korean:
  permission: debe.korean.cmd
  description: Korean - Command
  usage: /Korean

permissions:
 debe:
  default: op
  description: DeBePlugins
  children:
   debe.korean.cmd:
    description: Korean - Command