name: ViewLocation
main: DeBePlugins\ViewLocation\ViewLocation
version: DeBe
api: [1.6.0]
author: DeBe

commands:
 viewlocation:
  permission: debe.viewlocation.cmd
  description: ViewLocation - Command
  usage: /ViewLocation <PlayerName>

permissions:
 debe:
  default: op
  description: DeBePlugins
  children:
   debe.viewlocation.cmd:
   	default: true;
    description: ViewLocation - Command