name: TeleportView
main: DeBePlugins\TeleportView\TeleportView
version: DeBe
api: [1.6.0]
author: DeBe

commands:
 teleportview:
  permission: debe.teleportview.cmd
  description: TeleportView - Command
  usage: /TeleportView

permissions:
 debe:
  default: op
  description: DeBePlugins
  children:
   debe.teleportview.cmd:
   	default: true
    description: TeleportView - Command