name: Login
main: DeBePlugins\Login\Login
version: DeBe
api: [1.6.0]
author: DeBe

commands:
 login:
  permission: debe.login.cmd
  description: Login - Command
  usage: /Login <Password>
 register:
  permission: debe.login.cmd
  description: Login - Command
  usage: /Register <Pasrword> <Password>

permissions:
 debe:
  default: op
  description: DeBePlugins
  children:
   debe.login.cmd:
    default: true;
    description: Login - Command