name: Delivery
main: DeBePlugins\Delivery\Delivery
version: DeBe
api: [1.6.0]
author: DeBe

commands:
 delivery:
  permission: debe.delivery.cmd
  description: Delivery - Command
  usage: /Delivery <PlayerName> <ItemID> <Amount>

permissions:
 debe:
  default: op
  description: DeBePlugins
  children:
   debe.delivery.cmd:
    default: true
    description: Delivery - Command