name: EazyCommand
main: DeBePlugins\EazyCommand\EazyCommand
version: DeBe
api: [1.6.0]
author: DeBe

commands:
 eazycommand:
  permission: debe.eazycommand.cmd
  description: EazyCommand - Command
  usage: /EazyCommand <Add|Del|Reset|List>

permissions:
 debe:
  default: op
  description: DeBePlugins
  children:
   debe.eazycommand:
    description: DeBe - [EazyCommand]
    children:
      debe.eazycommand.cmd:
       description: EazyCommand - Command
      debe.eazycommand.use:
       default: true
       description: EazyCommand - Use the shortcut