name: SimpleArea
main: SimpleArea\SimpleArea
version: 0.8-alpha
author: hm
api: [1.4.1]

commands:
 home:
   permission: simplearea.commands.home
 sethome:
   permission: simplearea.commands.sethome
 sellhome:
   permission: simplearea.commands.delhome
 buyhome:
   permission: simplearea.commands.buyhome
 homelist:
   permission: simplearea.commands.homelist
 rent:
   permission: simplearea.commands.rent
 invite:
   permission: simplearea.commands.invite
 inviteclear:
   permission: simplearea.commands.inviteclear
 welcome:
   permission: simplearea.commands.welcome
 sa:
   permission: simplearea.commands.simplearea
   description: SimpleArea control commands
 yap:
   permission: simplearea.commands.yap
   description: SimpleArea control commands

permissions:
 simplearea.commands.home:
  default: true
 simplearea.commands.sethome:
  default: true
 simplearea.commands.buyhome:
  default: true
 simplearea.commands.homelist:
  default: true
 simplearea.commands.rent:
  default: true
 simplearea.commands.invite:
  default: true
 simplearea.commands.inviteclear:
  default: true
 simplearea.commands.welcome:
  default: true
 simplearea.commands.simplearea:
  default: OP
 simplearea.commands.yap:
  default: OP